# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-18 20:01
from __future__ import unicode_literals
from django.db import migrations


def forward_func(apps, schema_editor):
    Configuration = apps.get_model('groucho', 'Configuration')
    db_alias = schema_editor.connection.alias
    Configuration.objects.using(db_alias).bulk_create([
        Configuration(
            invalid_user_message='Unknown user',
            invalid_password_message='Password incorrect'
        )
    ])


def reverse_func(apps, schema_editor):
    Configuration = apps.get_model('groucho', 'Configuratino')
    db_alias = schema_editor.connection.alias
    Configuration.objects.using(db_alias).all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('groucho', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(forward_func, reverse_func)
    ]
