# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-20 15:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groucho', '0002_auto_20180118_1532'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProtectedUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='attemptuser',
            name='protected',
            field=models.BooleanField(default=False),
        ),
    ]
