# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-20 16:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groucho', '0003_auto_20180120_1057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attemptuser',
            name='protected',
        ),
    ]
